# Generated by Django 4.2.7 on 2025-09-26 22:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sc', models.CharField(max_length=20, unique=True, verbose_name='Numero de SC')),
                ('analitica', models.CharField(help_text='Formato: MX seguido de 7 numeros. Ejemplo: MX1234567', max_length=9, validators=[django.core.validators.RegexValidator(code='analitica_invalida', message='La analitica debe tener el formato MX seguido de 7 numeros. Ejemplo: MX1234567', regex='^MX\\d{7}$')])),
                ('descripcion', models.TextField(help_text='Descripcion detallada de lo que se necesita', verbose_name='Descripcion')),
                ('presupuesto_estimado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Presupuesto Estimado')),
                ('presupuesto_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Presupuesto Maximo Aprobado')),
                ('archivo_pdf', models.FileField(help_text='Adjuntar documento PDF de la solicitud', upload_to='solicitudes/pdf/', verbose_name='Archivo PDF')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Validacion'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cotizacion', 'En Cotizacion'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('comentario_rechazo', models.TextField(blank=True, verbose_name='Comentario de Rechazo')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Compra',
                'verbose_name_plural': 'Solicitudes de Compra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripcion detallada del producto o servicio', max_length=200, verbose_name='Descripcion del Item')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad requerida', max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por unidad', max_digits=10, verbose_name='Precio Unitario')),
                ('precio_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Precio Total')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='solicitudes.solicitudcompra')),
            ],
            options={
                'verbose_name': 'Item de Solicitud',
                'verbose_name_plural': 'Items de Solicitud',
            },
        ),
    ]
