# Generated by Django 4.2.7 on 2025-09-30 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='presupuesto_estimado',
        ),
    ]
