# Generated by Django 4.2.7 on 2025-10-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_remove_solicitudcompra_presupuesto_estimado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='solicitudcompra',
            name='numero_sc',
            field=models.CharField(help_text='Ingrese un número único para la solicitud. Ejemplo: SC-2024-001', max_length=20, unique=True, verbose_name='Numero de SC'),
        ),
    ]
