# Generated by Django 4.2.7 on 2025-10-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_solicitudcompra_prioridad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='codificacion',
            field=models.CharField(choices=[('A', 'A - EPP. Equipo de protección personal'), ('B', 'B - Equipos LOTO'), ('C', 'C - FORMACIONES'), ('D', 'D - UNIFORMES'), ('E', 'E - GESTIÓN DE PROYECTOS'), ('F', 'F - VEHÍCULOS'), ('G', 'G - GASTOS MÉDICOS EVENTUALES'), ('H', 'H - GASTOS COVID'), ('I', 'I - HERRAMIENTA MENOR'), ('J', 'J - EQUIPO DE MANIOBRA EN MT Y AT'), ('K', 'K - CONSUMIBLES'), ('L', 'L - SERVICIOS'), ('M', 'M - HERRAMIENTA CALIBRADA Y CALIBRACIONES'), ('N', 'N - HERRAMIENTA ESPECIALIZADA'), ('O', 'O - ÚTILES DE IZAJE Y MANIOBRA')], default='K', help_text='Seleccione la categoría de la compra', max_length=1, verbose_name='Codificación de Compra'),
        ),
    ]
