# Generated by Django 4.2.7 on 2025-10-31 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_solicitudcompra_codificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemSolicitud',
        ),
    ]
