# Generated by Django 4.2.7 on 2025-10-27 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='tipo_usuario',
            field=models.CharField(choices=[('solicitante', 'Usuario Solicitante'), ('jefe_proyectos', 'Jefe de Proyectos'), ('jefe_compras', 'Jefe de Compras'), ('jefe_financiero', 'Jefe Financiero'), ('proveedor', 'Proveedor'), ('admin_general', 'Administrador General')], default='solicitante', max_length=20),
        ),
    ]
