# Generated by Django 4.2.7 on 2025-11-02 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_proveedor_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['razon_social'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='direccion',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ambito',
            field=models.CharField(choices=[('local', 'Local'), ('nacional', 'Nacional'), ('internacional', 'Internacional')], default='nacional', max_length=20, verbose_name='Ámbito de Operación'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='banco',
            field=models.CharField(default='Banco por definir', help_text='Nombre del banco', max_length=100),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cartera_servicios',
            field=models.TextField(blank=True, default='Servicios por definir', help_text='Descripción detallada de los servicios o productos que ofrece', verbose_name='Cartera de Servicios/Productos'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cedula_situacion_fiscal',
            field=models.CharField(default='Por definir', help_text='Constancia de situación fiscal', max_length=50, verbose_name='Cédula de Situación Fiscal'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='clabe_interbancaria',
            field=models.CharField(blank=True, default='123456789123456789', help_text='18 dígitos', max_length=18, verbose_name='CLABE Interbancaria'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='curp_representante',
            field=models.CharField(blank=True, default='por definir', max_length=18, verbose_name='CURP del Representante'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion_fiscal',
            field=models.TextField(default='Dirección por definir', verbose_name='Dirección Fiscal'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='esta_activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='numero_proveedor',
            field=models.CharField(default='PROV-TEMP', help_text='Número único identificador del proveedor', max_length=20, unique=True, verbose_name='Número de Proveedor'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='representante_legal',
            field=models.CharField(default='Por definir', max_length=255, verbose_name='Representante Legal'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='swift_code',
            field=models.CharField(blank=True, default='por definir', help_text='Para transferencias internacionales', max_length=11, verbose_name='Código SWIFT'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono_emergencia',
            field=models.CharField(blank=True, default='9711234567', max_length=15, verbose_name='Teléfono de Emergencia'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_proveedor',
            field=models.CharField(choices=[('bienes', 'Proveedor de Bienes'), ('servicios', 'Proveedor de Servicios'), ('ambos', 'Proveedor de Bienes y Servicios')], default='bienes', max_length=20, verbose_name='Tipo de Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email_contacto',
            field=models.EmailField(default='contacto@proveedor.com', max_length=254, verbose_name='Email de Contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='numero_cuenta',
            field=models.CharField(default='Por definir', max_length=20, verbose_name='Número de Cuenta'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(default='Razón Social por definir', max_length=255, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(default='XAXX010101000', help_text='Registro Federal de Contribuyentes', max_length=13, unique=True, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_contacto',
            field=models.CharField(default='Por definir', max_length=15, verbose_name='Teléfono de Contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='terminos_pago',
            field=models.IntegerField(default=30, help_text='Días para pago', verbose_name='Términos de Pago'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedor_perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
