# Generated by Django 4.2.7 on 2025-11-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_proveedor_options_remove_proveedor_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='clabe_interbancaria',
            field=models.CharField(blank=True, default='', help_text='18 dígitos', max_length=18, verbose_name='CLABE Interbancaria'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='curp_representante',
            field=models.CharField(blank=True, default='', max_length=18, verbose_name='CURP del Representante'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='swift_code',
            field=models.CharField(blank=True, default='', help_text='Para transferencias internacionales', max_length=11, verbose_name='Código SWIFT'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_emergencia',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Teléfono de Emergencia'),
        ),
    ]
