# Generated by Django 4.2.7 on 2025-11-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_proveedor_clabe_interbancaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(default='Por definir', max_length=255, verbose_name='Razón Social'),
        ),
    ]
