# Generated by Django 4.2.7 on 2025-11-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_proveedor_razon_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analitica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del proyecto (ej: MX1234567)', max_length=50, unique=True, verbose_name='Código de Analítica')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del proyecto (ej: Mantenimiento Río Verde)', max_length=255, verbose_name='Nombre del Proyecto')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del proyecto', verbose_name='Descripción')),
                ('esta_activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analítica',
                'verbose_name_plural': 'Analíticas',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='tipo_usuario',
            field=models.CharField(choices=[('solicitante', 'Usuario Solicitante'), ('jefe_proyectos', 'Jefe de Proyectos'), ('jefe_compras', 'Jefe de Compras'), ('jefe_financiero', 'Jefe Financiero'), ('rh', 'Recursos Humanos'), ('proveedor', 'Proveedor'), ('admin_general', 'Administrador General')], default='solicitante', max_length=20),
        ),
    ]
