# Generated by Django 4.2.7 on 2025-11-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_analitica_alter_usuariopersonalizado_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellido(s)')),
                ('rfc', models.CharField(help_text='Clave única de identificación fiscal.', max_length=13, unique=True, verbose_name='RFC (Registro Federal de Contribuyentes)')),
                ('puesto', models.CharField(max_length=100, verbose_name='Puesto o Cargo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trabajador (Recurso)',
                'verbose_name_plural': 'Trabajadores (Recursos)',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
