# Generated by Django 4.2.7 on 2025-11-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='esta_activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
